/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiHintOption = 'IMAGE_ITEM' | 'VIDEO_ITEM_SEGMENT' | 'TEXT' | 'EXTERNAL_IMAGE' | 'EXTERNAL_VIDEO';

export const ApiHintOption = {
    IMAGE_ITEM: 'IMAGE_ITEM' as ApiHintOption,
    VIDEO_ITEM_SEGMENT: 'VIDEO_ITEM_SEGMENT' as ApiHintOption,
    TEXT: 'TEXT' as ApiHintOption,
    EXTERNAL_IMAGE: 'EXTERNAL_IMAGE' as ApiHintOption,
    EXTERNAL_VIDEO: 'EXTERNAL_VIDEO' as ApiHintOption
};

