/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTaskStatus } from './apiTaskStatus';


export interface ApiTaskOverview { 
    id: string;
    name: string;
    type: string;
    group: string;
    duration: number;
    taskId: string;
    status: ApiTaskStatus;
    started?: number;
    ended?: number;
}

