/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiTaskOption = 'HIDDEN_RESULTS' | 'MAP_TO_SEGMENT' | 'PROLONG_ON_SUBMISSION';

export const ApiTaskOption = {
    HIDDEN_RESULTS: 'HIDDEN_RESULTS' as ApiTaskOption,
    MAP_TO_SEGMENT: 'MAP_TO_SEGMENT' as ApiTaskOption,
    PROLONG_ON_SUBMISSION: 'PROLONG_ON_SUBMISSION' as ApiTaskOption
};

