/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiTargetType = 'JUDGEMENT' | 'JUDGEMENT_WITH_VOTE' | 'MEDIA_ITEM' | 'MEDIA_ITEM_TEMPORAL_RANGE' | 'TEXT';

export const ApiTargetType = {
    JUDGEMENT: 'JUDGEMENT' as ApiTargetType,
    JUDGEMENT_WITH_VOTE: 'JUDGEMENT_WITH_VOTE' as ApiTargetType,
    MEDIA_ITEM: 'MEDIA_ITEM' as ApiTargetType,
    MEDIA_ITEM_TEMPORAL_RANGE: 'MEDIA_ITEM_TEMPORAL_RANGE' as ApiTargetType,
    TEXT: 'TEXT' as ApiTargetType
};

