/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiTemporalUnit = 'FRAME_NUMBER' | 'SECONDS' | 'MILLISECONDS' | 'TIMECODE';

export const ApiTemporalUnit = {
    FRAME_NUMBER: 'FRAME_NUMBER' as ApiTemporalUnit,
    SECONDS: 'SECONDS' as ApiTemporalUnit,
    MILLISECONDS: 'MILLISECONDS' as ApiTemporalUnit,
    TIMECODE: 'TIMECODE' as ApiTemporalUnit
};

