/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiTaskStatus = 'NO_TASK' | 'CREATED' | 'PREPARING' | 'RUNNING' | 'ENDED' | 'IGNORED';

export const ApiTaskStatus = {
    NO_TASK: 'NO_TASK' as ApiTaskStatus,
    CREATED: 'CREATED' as ApiTaskStatus,
    PREPARING: 'PREPARING' as ApiTaskStatus,
    RUNNING: 'RUNNING' as ApiTaskStatus,
    ENDED: 'ENDED' as ApiTaskStatus,
    IGNORED: 'IGNORED' as ApiTaskStatus
};

