/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiTargetOption = 'SINGLE_MEDIA_ITEM' | 'SINGLE_MEDIA_SEGMENT' | 'JUDGEMENT' | 'VOTE' | 'TEXT';

export const ApiTargetOption = {
    SINGLE_MEDIA_ITEM: 'SINGLE_MEDIA_ITEM' as ApiTargetOption,
    SINGLE_MEDIA_SEGMENT: 'SINGLE_MEDIA_SEGMENT' as ApiTargetOption,
    JUDGEMENT: 'JUDGEMENT' as ApiTargetOption,
    VOTE: 'VOTE' as ApiTargetOption,
    TEXT: 'TEXT' as ApiTargetOption
};

