/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DresInfo { 
    version: string;
    startTime: number;
    uptime: number;
    os?: string;
    jvm?: string;
    args?: string;
    cores?: number;
    freeMemory?: number;
    totalMemory?: number;
    load?: number;
    availableSeverThreads?: number;
}

