/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type QueryEventCategory = 'TEXT' | 'IMAGE' | 'SKETCH' | 'FILTER' | 'BROWSING' | 'COOPERATION' | 'OTHER';

export const QueryEventCategory = {
    TEXT: 'TEXT' as QueryEventCategory,
    IMAGE: 'IMAGE' as QueryEventCategory,
    SKETCH: 'SKETCH' as QueryEventCategory,
    FILTER: 'FILTER' as QueryEventCategory,
    BROWSING: 'BROWSING' as QueryEventCategory,
    COOPERATION: 'COOPERATION' as QueryEventCategory,
    OTHER: 'OTHER' as QueryEventCategory
};

