/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QueryEvent { 
    timestamp: number;
    category: QueryEvent.CategoryEnum;
    type: string;
    value: string;
}
export namespace QueryEvent {
    export type CategoryEnum = 'TEXT' | 'IMAGE' | 'SKETCH' | 'FILTER' | 'BROWSING' | 'COOPERATION' | 'OTHER';
    export const CategoryEnum = {
        TEXT: 'TEXT' as CategoryEnum,
        IMAGE: 'IMAGE' as CategoryEnum,
        SKETCH: 'SKETCH' as CategoryEnum,
        FILTER: 'FILTER' as CategoryEnum,
        BROWSING: 'BROWSING' as CategoryEnum,
        COOPERATION: 'COOPERATION' as CategoryEnum,
        OTHER: 'OTHER' as CategoryEnum
    };
}


