/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.3
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RunManagerStatus = 'CREATED' | 'ACTIVE' | 'TERMINATED';

export const RunManagerStatus = {
    CREATED: 'CREATED' as RunManagerStatus,
    ACTIVE: 'ACTIVE' as RunManagerStatus,
    TERMINATED: 'TERMINATED' as RunManagerStatus
};

