/**
 * DRES API
 * API for DRES (Distributed Retrieval Evaluation Server), Version 1.0
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDetails { 
    id: string;
    username: string;
    role: UserDetails.RoleEnum;
    sessionId?: string;
}
export namespace UserDetails {
    export type RoleEnum = 'ADMIN' | 'JUDGE' | 'VIEWER' | 'PARTICIPANT';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        JUDGE: 'JUDGE' as RoleEnum,
        VIEWER: 'VIEWER' as RoleEnum,
        PARTICIPANT: 'PARTICIPANT' as RoleEnum
    };
}


