export * from './default.service';
import { DefaultService } from './default.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './misc.service';
import { MiscService } from './misc.service';
export * from './object.service';
import { ObjectService } from './object.service';
export * from './segment.service';
import { SegmentService } from './segment.service';
export * from './segments.service';
import { SegmentsService } from './segments.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './tag.service';
import { TagService } from './tag.service';
export const APIS = [DefaultService, MetadataService, MiscService, ObjectService, SegmentService, SegmentsService, SessionService, StatusService, TagService];
