export * from './evaluation.service';
import { EvaluationService } from './evaluation.service';
export * from './evaluationClient.service';
import { EvaluationClientService } from './evaluationClient.service';
export * from './log.service';
import { LogService } from './log.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './submission.service';
import { SubmissionService } from './submission.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [EvaluationService, EvaluationClientService, LogService, StatusService, SubmissionService, UserService];
