/**
 * Cineast RESTful API
 * Cineast is vitrivr\'s content-based multimedia retrieval engine. This is it\'s RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaObjectDescriptor { 
    objectId?: string;
    name?: string;
    path?: string;
    mediatype?: MediaObjectDescriptor.MediatypeEnum;
    exists?: boolean;
    contentURL?: string;
}
export namespace MediaObjectDescriptor {
    export type MediatypeEnum = 'VIDEO' | 'IMAGE' | 'AUDIO' | 'MODEL3D' | 'IMAGE_SEQUENCE' | 'UNKNOWN';
    export const MediatypeEnum = {
        VIDEO: 'VIDEO' as MediatypeEnum,
        IMAGE: 'IMAGE' as MediatypeEnum,
        AUDIO: 'AUDIO' as MediatypeEnum,
        MODEL3D: 'MODEL3D' as MediatypeEnum,
        IMAGESEQUENCE: 'IMAGE_SEQUENCE' as MediatypeEnum,
        UNKNOWN: 'UNKNOWN' as MediatypeEnum
    };
}


