/**
 * Cineast RESTful API
 * Cineast is vitrivr\'s content-based multimedia retrieval engine. This is it\'s RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MetadataAccessSpecification { 
    type?: MetadataAccessSpecification.TypeEnum;
    domain?: string;
    key?: string;
}
export namespace MetadataAccessSpecification {
    export type TypeEnum = 'OBJECT' | 'SEGMENT';
    export const TypeEnum = {
        Object: 'OBJECT' as TypeEnum,
        Segment: 'SEGMENT' as TypeEnum
    };
}


