/**
 * Cineast RESTful API
 * Cineast is vitrivr\'s content-based multimedia retrieval engine. This is it\'s RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QueryTerm { 
    categories: Array<string>;
    type: QueryTerm.TypeEnum;
    data: string;
}
export namespace QueryTerm {
    export type TypeEnum = 'IMAGE' | 'AUDIO' | 'MODEL3D' | 'LOCATION' | 'PARAMETERISED_LOCATION' | 'TIME' | 'TEXT' | 'TAG' | 'SEMANTIC' | 'SKELETON' | 'ID' | 'BOOLEAN';
    export const TypeEnum = {
        Image: 'IMAGE' as TypeEnum,
        Audio: 'AUDIO' as TypeEnum,
        Model3D: 'MODEL3D' as TypeEnum,
        Location: 'LOCATION' as TypeEnum,
        ParameterisedLocation: 'PARAMETERISED_LOCATION' as TypeEnum,
        Time: 'TIME' as TypeEnum,
        Text: 'TEXT' as TypeEnum,
        Tag: 'TAG' as TypeEnum,
        Semantic: 'SEMANTIC' as TypeEnum,
        Skeleton: 'SKELETON' as TypeEnum,
        Id: 'ID' as TypeEnum,
        Boolean: 'BOOLEAN' as TypeEnum
    };
}


